//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_JobApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class JOBSEEKER
    {
        public string userid { get; set; }
        public string ho { get; set; }
        public string ten { get; set; }
        public string ngsinh { get; set; }
        public string cmnd { get; set; }
        public string gioitinh { get; set; }
        public string diachi { get; set; }
        public string sdt { get; set; }
        public string email { get; set; }
        public string thongtin { get; set; }
    }
}
