//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_JobApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class UNGTUYEN
    {
        public string userid { get; set; }
        public string jobid { get; set; }
        public string tencv { get; set; }
        public string thoigian { get; set; }
        public string congty { get; set; }
        public string trangthaiphanhoi { get; set; }
    
        public virtual ACCOUNT ACCOUNT { get; set; }
        public virtual COMPANY COMPANY { get; set; }
        public virtual CONGVIEC CONGVIEC { get; set; }
    }
}
